### ISSUE TITLE
v8-list is released but not crawled

### ISSUE THREAD

**Issue by samm-git** [Salamek/blacklist#20]
See https://www.mfcr.cz/assets/cs/media/Zverejnovane-udaje-ze-Seznamu-nepovolenych-internetovych-her_v8.pdf

**Comment by Salamek** [comment]
@samm-git there was too high RAM usage on my cheap VPS, thats why celery (background job downloading PDFs) was unable to run properly... "fixed" for now

**Comment by samm-git** [comment]
Great, thank you!
